"""The LR35902 Instruction set as a big JSON blob."""


class LR35902Data():
    """The LR35902 Instruction set as a big JSON blob."""

    __slots__ = ('json', 'length')

    def __repr__(self):
        return "None"

    def __str__(self):
        return f"Raw minified JSON {self.length} bytes in length"

    def __new__(cls):
        """Initialize the JSON blob."""
        if not hasattr(cls, 'instance'):
            cls.instance = super(LR35902Data, cls).__new__(cls)
            cls.instance.json = """
{"$00":{"mnemonic":"nop","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr\
":"$00"},"$01":{"mnemonic":"ld","length":3,"cycles":[12],"flags":["-","-","-","-\
"],"addr":"$01","operand1":"bc","operand2":"d16"},"$02":{"mnemonic":"ld","length\
":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$02","operand1":"(bc)","opera\
nd2":"a"},"$03":{"mnemonic":"inc","length":1,"cycles":[8],"flags":["-","-","-","\
-"],"addr":"$03","operand1":"bc"},"$04":{"mnemonic":"inc","length":1,"cycles":[4\
],"flags":["z","0","h","-"],"addr":"$04","operand1":"b"},"$05":{"mnemonic":"dec"\
,"length":1,"cycles":[4],"flags":["z","1","h","-"],"addr":"$05","operand1":"b"},\
"$06":{"mnemonic":"ld","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":\
"$06","operand1":"b","operand2":"d8"},"$07":{"mnemonic":"rlca","length":1,"cycle\
s":[4],"flags":["0","0","0","c"],"addr":"$07"},"$08":{"mnemonic":"ld","length":3\
,"cycles":[20],"flags":["-","-","-","-"],"addr":"$08","operand1":"(a16)","operan\
d2":"sp"},"$09":{"mnemonic":"add","length":1,"cycles":[8],"flags":["-","0","h","\
c"],"addr":"$09","operand1":"hl","operand2":"bc"},"$0a":{"mnemonic":"ld","length\
":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$0a","operand1":"a","operand2\
":"(bc)"},"$0b":{"mnemonic":"dec","length":1,"cycles":[8],"flags":["-","-","-","\
-"],"addr":"$0b","operand1":"bc"},"$0c":{"mnemonic":"inc","length":1,"cycles":[4\
],"flags":["z","0","h","-"],"addr":"$0c","operand1":"c"},"$0d":{"mnemonic":"dec"\
,"length":1,"cycles":[4],"flags":["z","1","h","-"],"addr":"$0d","operand1":"c"},\
"$0e":{"mnemonic":"ld","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":\
"$0e","operand1":"c","operand2":"d8"},"$0f":{"mnemonic":"rrca","length":1,"cycle\
s":[4],"flags":["0","0","0","c"],"addr":"$0f"},"$10":{"mnemonic":"stop","length"\
:2,"cycles":[4],"flags":["-","-","-","-"],"addr":"$10","operand1":"0"},"$11":{"m\
nemonic":"ld","length":3,"cycles":[12],"flags":["-","-","-","-"],"addr":"$11","o\
perand1":"de","operand2":"d16"},"$12":{"mnemonic":"ld","length":1,"cycles":[8],"\
flags":["-","-","-","-"],"addr":"$12","operand1":"(de)","operand2":"a"},"$13":{"\
mnemonic":"inc","length":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$13","\
operand1":"de"},"$14":{"mnemonic":"inc","length":1,"cycles":[4],"flags":["z","0"\
,"h","-"],"addr":"$14","operand1":"d"},"$15":{"mnemonic":"dec","length":1,"cycle\
s":[4],"flags":["z","1","h","-"],"addr":"$15","operand1":"d"},"$16":{"mnemonic":\
"ld","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$16","operand1":"\
d","operand2":"d8"},"$17":{"mnemonic":"rla","length":1,"cycles":[4],"flags":["0"\
,"0","0","c"],"addr":"$17"},"$18":{"mnemonic":"jr","length":2,"cycles":[12],"fla\
gs":["-","-","-","-"],"addr":"$18","operand1":"r8"},"$19":{"mnemonic":"add","len\
gth":1,"cycles":[8],"flags":["-","0","h","c"],"addr":"$19","operand1":"hl","oper\
and2":"de"},"$1a":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-",\
"-"],"addr":"$1a","operand1":"a","operand2":"(de)"},"$1b":{"mnemonic":"dec","len\
gth":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$1b","operand1":"de"},"$1c\
":{"mnemonic":"inc","length":1,"cycles":[4],"flags":["z","0","h","-"],"addr":"$1\
c","operand1":"e"},"$1d":{"mnemonic":"dec","length":1,"cycles":[4],"flags":["z",\
"1","h","-"],"addr":"$1d","operand1":"e"},"$1e":{"mnemonic":"ld","length":2,"cyc\
les":[8],"flags":["-","-","-","-"],"addr":"$1e","operand1":"e","operand2":"d8"},\
"$1f":{"mnemonic":"rra","length":1,"cycles":[4],"flags":["0","0","0","c"],"addr"\
:"$1f"},"$20":{"mnemonic":"jr","length":2,"cycles":[12,8],"flags":["-","-","-","\
-"],"addr":"$20","operand1":"nz","operand2":"r8"},"$21":{"mnemonic":"ld","length\
":3,"cycles":[12],"flags":["-","-","-","-"],"addr":"$21","operand1":"hl","operan\
d2":"d16"},"$22":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","\
-"],"addr":"$22","operand1":"(hl+)","operand2":"a"},"$23":{"mnemonic":"inc","len\
gth":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$23","operand1":"hl"},"$24\
":{"mnemonic":"inc","length":1,"cycles":[4],"flags":["z","0","h","-"],"addr":"$2\
4","operand1":"h"},"$25":{"mnemonic":"dec","length":1,"cycles":[4],"flags":["z",\
"1","h","-"],"addr":"$25","operand1":"h"},"$26":{"mnemonic":"ld","length":2,"cyc\
les":[8],"flags":["-","-","-","-"],"addr":"$26","operand1":"h","operand2":"d8"},\
"$27":{"mnemonic":"daa","length":1,"cycles":[4],"flags":["z","-","0","c"],"addr"\
:"$27"},"$28":{"mnemonic":"jr","length":2,"cycles":[12,8],"flags":["-","-","-","\
-"],"addr":"$28","operand1":"z","operand2":"r8"},"$29":{"mnemonic":"add","length\
":1,"cycles":[8],"flags":["-","0","h","c"],"addr":"$29","operand1":"hl","operand\
2":"hl"},"$2a":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-"\
],"addr":"$2a","operand1":"a","operand2":"(hl+)"},"$2b":{"mnemonic":"dec","lengt\
h":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$2b","operand1":"hl"},"$2c":\
{"mnemonic":"inc","length":1,"cycles":[4],"flags":["z","0","h","-"],"addr":"$2c"\
,"operand1":"l"},"$2d":{"mnemonic":"dec","length":1,"cycles":[4],"flags":["z","1\
","h","-"],"addr":"$2d","operand1":"l"},"$2e":{"mnemonic":"ld","length":2,"cycle\
s":[8],"flags":["-","-","-","-"],"addr":"$2e","operand1":"l","operand2":"d8"},"$\
2f":{"mnemonic":"cpl","length":1,"cycles":[4],"flags":["-","1","1","-"],"addr":"\
$2f"},"$30":{"mnemonic":"jr","length":2,"cycles":[12,8],"flags":["-","-","-","-"\
],"addr":"$30","operand1":"nc","operand2":"r8"},"$31":{"mnemonic":"ld","length":\
3,"cycles":[12],"flags":["-","-","-","-"],"addr":"$31","operand1":"sp","operand2\
":"d16"},"$32":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-"\
],"addr":"$32","operand1":"(hl-)","operand2":"a"},"$33":{"mnemonic":"inc","lengt\
h":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$33","operand1":"sp"},"$34":\
{"mnemonic":"inc","length":1,"cycles":[12],"flags":["z","0","h","-"],"addr":"$34\
","operand1":"(hl)"},"$35":{"mnemonic":"dec","length":1,"cycles":[12],"flags":["\
z","1","h","-"],"addr":"$35","operand1":"(hl)"},"$36":{"mnemonic":"ld","length":\
2,"cycles":[12],"flags":["-","-","-","-"],"addr":"$36","operand1":"(hl)","operan\
d2":"d8"},"$37":{"mnemonic":"scf","length":1,"cycles":[4],"flags":["-","0","0","\
1"],"addr":"$37"},"$38":{"mnemonic":"jr","length":2,"cycles":[12,8],"flags":["-"\
,"-","-","-"],"addr":"$38","operand1":"c","operand2":"r8"},"$39":{"mnemonic":"ad\
d","length":1,"cycles":[8],"flags":["-","0","h","c"],"addr":"$39","operand1":"hl\
","operand2":"sp"},"$3a":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","\
-","-","-"],"addr":"$3a","operand1":"a","operand2":"(hl-)"},"$3b":{"mnemonic":"d\
ec","length":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$3b","operand1":"s\
p"},"$3c":{"mnemonic":"inc","length":1,"cycles":[4],"flags":["z","0","h","-"],"a\
ddr":"$3c","operand1":"a"},"$3d":{"mnemonic":"dec","length":1,"cycles":[4],"flag\
s":["z","1","h","-"],"addr":"$3d","operand1":"a"},"$3e":{"mnemonic":"ld","length\
":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$3e","operand1":"a","operand2\
":"d8"},"$3f":{"mnemonic":"ccf","length":1,"cycles":[4],"flags":["-","0","0","c"\
],"addr":"$3f"},"$40":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-",\
"-","-"],"addr":"$40","operand1":"b","operand2":"b"},"$41":{"mnemonic":"ld","len\
gth":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$41","operand1":"b","opera\
nd2":"c"},"$42":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-\
"],"addr":"$42","operand1":"b","operand2":"d"},"$43":{"mnemonic":"ld","length":1\
,"cycles":[4],"flags":["-","-","-","-"],"addr":"$43","operand1":"b","operand2":"\
e"},"$44":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"ad\
dr":"$44","operand1":"b","operand2":"h"},"$45":{"mnemonic":"ld","length":1,"cycl\
es":[4],"flags":["-","-","-","-"],"addr":"$45","operand1":"b","operand2":"l"},"$\
46":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$\
46","operand1":"b","operand2":"(hl)"},"$47":{"mnemonic":"ld","length":1,"cycles"\
:[4],"flags":["-","-","-","-"],"addr":"$47","operand1":"b","operand2":"a"},"$48"\
:{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$48"\
,"operand1":"c","operand2":"b"},"$49":{"mnemonic":"ld","length":1,"cycles":[4],"\
flags":["-","-","-","-"],"addr":"$49","operand1":"c","operand2":"c"},"$4a":{"mne\
monic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$4a","oper\
and1":"c","operand2":"d"},"$4b":{"mnemonic":"ld","length":1,"cycles":[4],"flags"\
:["-","-","-","-"],"addr":"$4b","operand1":"c","operand2":"e"},"$4c":{"mnemonic"\
:"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$4c","operand1":\
"c","operand2":"h"},"$4d":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-",\
"-","-","-"],"addr":"$4d","operand1":"c","operand2":"l"},"$4e":{"mnemonic":"ld",\
"length":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$4e","operand1":"c","o\
perand2":"(hl)"},"$4f":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-"\
,"-","-"],"addr":"$4f","operand1":"c","operand2":"a"},"$50":{"mnemonic":"ld","le\
ngth":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$50","operand1":"d","oper\
and2":"b"},"$51":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","\
-"],"addr":"$51","operand1":"d","operand2":"c"},"$52":{"mnemonic":"ld","length":\
1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$52","operand1":"d","operand2":\
"d"},"$53":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"a\
ddr":"$53","operand1":"d","operand2":"e"},"$54":{"mnemonic":"ld","length":1,"cyc\
les":[4],"flags":["-","-","-","-"],"addr":"$54","operand1":"d","operand2":"h"},"\
$55":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"\
$55","operand1":"d","operand2":"l"},"$56":{"mnemonic":"ld","length":1,"cycles":[\
8],"flags":["-","-","-","-"],"addr":"$56","operand1":"d","operand2":"(hl)"},"$57\
":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$57\
","operand1":"d","operand2":"a"},"$58":{"mnemonic":"ld","length":1,"cycles":[4],\
"flags":["-","-","-","-"],"addr":"$58","operand1":"e","operand2":"b"},"$59":{"mn\
emonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$59","ope\
rand1":"e","operand2":"c"},"$5a":{"mnemonic":"ld","length":1,"cycles":[4],"flags\
":["-","-","-","-"],"addr":"$5a","operand1":"e","operand2":"d"},"$5b":{"mnemonic\
":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$5b","operand1"\
:"e","operand2":"e"},"$5c":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-"\
,"-","-","-"],"addr":"$5c","operand1":"e","operand2":"h"},"$5d":{"mnemonic":"ld"\
,"length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$5d","operand1":"e","\
operand2":"l"},"$5e":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","\
-","-"],"addr":"$5e","operand1":"e","operand2":"(hl)"},"$5f":{"mnemonic":"ld","l\
ength":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$5f","operand1":"e","ope\
rand2":"a"},"$60":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-",\
"-"],"addr":"$60","operand1":"h","operand2":"b"},"$61":{"mnemonic":"ld","length"\
:1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$61","operand1":"h","operand2"\
:"c"},"$62":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"\
addr":"$62","operand1":"h","operand2":"d"},"$63":{"mnemonic":"ld","length":1,"cy\
cles":[4],"flags":["-","-","-","-"],"addr":"$63","operand1":"h","operand2":"e"},\
"$64":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":\
"$64","operand1":"h","operand2":"h"},"$65":{"mnemonic":"ld","length":1,"cycles":\
[4],"flags":["-","-","-","-"],"addr":"$65","operand1":"h","operand2":"l"},"$66":\
{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$66",\
"operand1":"h","operand2":"(hl)"},"$67":{"mnemonic":"ld","length":1,"cycles":[4]\
,"flags":["-","-","-","-"],"addr":"$67","operand1":"h","operand2":"a"},"$68":{"m\
nemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$68","op\
erand1":"l","operand2":"b"},"$69":{"mnemonic":"ld","length":1,"cycles":[4],"flag\
s":["-","-","-","-"],"addr":"$69","operand1":"l","operand2":"c"},"$6a":{"mnemoni\
c":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$6a","operand1\
":"l","operand2":"d"},"$6b":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-\
","-","-","-"],"addr":"$6b","operand1":"l","operand2":"e"},"$6c":{"mnemonic":"ld\
","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$6c","operand1":"l",\
"operand2":"h"},"$6d":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-",\
"-","-"],"addr":"$6d","operand1":"l","operand2":"l"},"$6e":{"mnemonic":"ld","len\
gth":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$6e","operand1":"l","opera\
nd2":"(hl)"},"$6f":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-"\
,"-"],"addr":"$6f","operand1":"l","operand2":"a"},"$70":{"mnemonic":"ld","length\
":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$70","operand1":"(hl)","opera\
nd2":"b"},"$71":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-\
"],"addr":"$71","operand1":"(hl)","operand2":"c"},"$72":{"mnemonic":"ld","length\
":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$72","operand1":"(hl)","opera\
nd2":"d"},"$73":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-\
"],"addr":"$73","operand1":"(hl)","operand2":"e"},"$74":{"mnemonic":"ld","length\
":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$74","operand1":"(hl)","opera\
nd2":"h"},"$75":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-\
"],"addr":"$75","operand1":"(hl)","operand2":"l"},"$76":{"mnemonic":"halt","leng\
th":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$76"},"$77":{"mnemonic":"ld\
","length":1,"cycles":[8],"flags":["-","-","-","-"],"addr":"$77","operand1":"(hl\
)","operand2":"a"},"$78":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","\
-","-","-"],"addr":"$78","operand1":"a","operand2":"b"},"$79":{"mnemonic":"ld","\
length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$79","operand1":"a","op\
erand2":"c"},"$7a":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-"\
,"-"],"addr":"$7a","operand1":"a","operand2":"d"},"$7b":{"mnemonic":"ld","length\
":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$7b","operand1":"a","operand2\
":"e"},"$7c":{"mnemonic":"ld","length":1,"cycles":[4],"flags":["-","-","-","-"],\
"addr":"$7c","operand1":"a","operand2":"h"},"$7d":{"mnemonic":"ld","length":1,"c\
ycles":[4],"flags":["-","-","-","-"],"addr":"$7d","operand1":"a","operand2":"l"}\
,"$7e":{"mnemonic":"ld","length":1,"cycles":[8],"flags":["-","-","-","-"],"addr"\
:"$7e","operand1":"a","operand2":"(hl)"},"$7f":{"mnemonic":"ld","length":1,"cycl\
es":[4],"flags":["-","-","-","-"],"addr":"$7f","operand1":"a","operand2":"a"},"$\
80":{"mnemonic":"add","length":1,"cycles":[4],"flags":["z","0","h","c"],"addr":"\
$80","operand1":"a","operand2":"b"},"$81":{"mnemonic":"add","length":1,"cycles":\
[4],"flags":["z","0","h","c"],"addr":"$81","operand1":"a","operand2":"c"},"$82":\
{"mnemonic":"add","length":1,"cycles":[4],"flags":["z","0","h","c"],"addr":"$82"\
,"operand1":"a","operand2":"d"},"$83":{"mnemonic":"add","length":1,"cycles":[4],\
"flags":["z","0","h","c"],"addr":"$83","operand1":"a","operand2":"e"},"$84":{"mn\
emonic":"add","length":1,"cycles":[4],"flags":["z","0","h","c"],"addr":"$84","op\
erand1":"a","operand2":"h"},"$85":{"mnemonic":"add","length":1,"cycles":[4],"fla\
gs":["z","0","h","c"],"addr":"$85","operand1":"a","operand2":"l"},"$86":{"mnemon\
ic":"add","length":1,"cycles":[8],"flags":["z","0","h","c"],"addr":"$86","operan\
d1":"a","operand2":"(hl)"},"$87":{"mnemonic":"add","length":1,"cycles":[4],"flag\
s":["z","0","h","c"],"addr":"$87","operand1":"a","operand2":"a"},"$88":{"mnemoni\
c":"adc","length":1,"cycles":[4],"flags":["z","0","h","c"],"addr":"$88","operand\
1":"a","operand2":"b"},"$89":{"mnemonic":"adc","length":1,"cycles":[4],"flags":[\
"z","0","h","c"],"addr":"$89","operand1":"a","operand2":"c"},"$8a":{"mnemonic":"\
adc","length":1,"cycles":[4],"flags":["z","0","h","c"],"addr":"$8a","operand1":"\
a","operand2":"d"},"$8b":{"mnemonic":"adc","length":1,"cycles":[4],"flags":["z",\
"0","h","c"],"addr":"$8b","operand1":"a","operand2":"e"},"$8c":{"mnemonic":"adc"\
,"length":1,"cycles":[4],"flags":["z","0","h","c"],"addr":"$8c","operand1":"a","\
operand2":"h"},"$8d":{"mnemonic":"adc","length":1,"cycles":[4],"flags":["z","0",\
"h","c"],"addr":"$8d","operand1":"a","operand2":"l"},"$8e":{"mnemonic":"adc","le\
ngth":1,"cycles":[8],"flags":["z","0","h","c"],"addr":"$8e","operand1":"a","oper\
and2":"(hl)"},"$8f":{"mnemonic":"adc","length":1,"cycles":[4],"flags":["z","0","\
h","c"],"addr":"$8f","operand1":"a","operand2":"a"},"$90":{"mnemonic":"sub","len\
gth":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$90","operand1":"b"},"$91"\
:{"mnemonic":"sub","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$91\
","operand1":"c"},"$92":{"mnemonic":"sub","length":1,"cycles":[4],"flags":["z","\
1","h","c"],"addr":"$92","operand1":"d"},"$93":{"mnemonic":"sub","length":1,"cyc\
les":[4],"flags":["z","1","h","c"],"addr":"$93","operand1":"e"},"$94":{"mnemonic\
":"sub","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$94","operand1\
":"h"},"$95":{"mnemonic":"sub","length":1,"cycles":[4],"flags":["z","1","h","c"]\
,"addr":"$95","operand1":"l"},"$96":{"mnemonic":"sub","length":1,"cycles":[8],"f\
lags":["z","1","h","c"],"addr":"$96","operand1":"(hl)"},"$97":{"mnemonic":"sub",\
"length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$97","operand1":"a"},"\
$98":{"mnemonic":"sbc","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":\
"$98","operand1":"a","operand2":"b"},"$99":{"mnemonic":"sbc","length":1,"cycles"\
:[4],"flags":["z","1","h","c"],"addr":"$99","operand1":"a","operand2":"c"},"$9a"\
:{"mnemonic":"sbc","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$9a\
","operand1":"a","operand2":"d"},"$9b":{"mnemonic":"sbc","length":1,"cycles":[4]\
,"flags":["z","1","h","c"],"addr":"$9b","operand1":"a","operand2":"e"},"$9c":{"m\
nemonic":"sbc","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$9c","o\
perand1":"a","operand2":"h"},"$9d":{"mnemonic":"sbc","length":1,"cycles":[4],"fl\
ags":["z","1","h","c"],"addr":"$9d","operand1":"a","operand2":"l"},"$9e":{"mnemo\
nic":"sbc","length":1,"cycles":[8],"flags":["z","1","h","c"],"addr":"$9e","opera\
nd1":"a","operand2":"(hl)"},"$9f":{"mnemonic":"sbc","length":1,"cycles":[4],"fla\
gs":["z","1","h","c"],"addr":"$9f","operand1":"a","operand2":"a"},"$a0":{"mnemon\
ic":"and","length":1,"cycles":[4],"flags":["z","0","1","0"],"addr":"$a0","operan\
d1":"b"},"$a1":{"mnemonic":"and","length":1,"cycles":[4],"flags":["z","0","1","0\
"],"addr":"$a1","operand1":"c"},"$a2":{"mnemonic":"and","length":1,"cycles":[4],\
"flags":["z","0","1","0"],"addr":"$a2","operand1":"d"},"$a3":{"mnemonic":"and","\
length":1,"cycles":[4],"flags":["z","0","1","0"],"addr":"$a3","operand1":"e"},"$\
a4":{"mnemonic":"and","length":1,"cycles":[4],"flags":["z","0","1","0"],"addr":"\
$a4","operand1":"h"},"$a5":{"mnemonic":"and","length":1,"cycles":[4],"flags":["z\
","0","1","0"],"addr":"$a5","operand1":"l"},"$a6":{"mnemonic":"and","length":1,"\
cycles":[8],"flags":["z","0","1","0"],"addr":"$a6","operand1":"(hl)"},"$a7":{"mn\
emonic":"and","length":1,"cycles":[4],"flags":["z","0","1","0"],"addr":"$a7","op\
erand1":"a"},"$a8":{"mnemonic":"xor","length":1,"cycles":[4],"flags":["z","0","0\
","0"],"addr":"$a8","operand1":"b"},"$a9":{"mnemonic":"xor","length":1,"cycles":\
[4],"flags":["z","0","0","0"],"addr":"$a9","operand1":"c"},"$aa":{"mnemonic":"xo\
r","length":1,"cycles":[4],"flags":["z","0","0","0"],"addr":"$aa","operand1":"d"\
},"$ab":{"mnemonic":"xor","length":1,"cycles":[4],"flags":["z","0","0","0"],"add\
r":"$ab","operand1":"e"},"$ac":{"mnemonic":"xor","length":1,"cycles":[4],"flags"\
:["z","0","0","0"],"addr":"$ac","operand1":"h"},"$ad":{"mnemonic":"xor","length"\
:1,"cycles":[4],"flags":["z","0","0","0"],"addr":"$ad","operand1":"l"},"$ae":{"m\
nemonic":"xor","length":1,"cycles":[8],"flags":["z","0","0","0"],"addr":"$ae","o\
perand1":"(hl)"},"$af":{"mnemonic":"xor","length":1,"cycles":[4],"flags":["z","0\
","0","0"],"addr":"$af","operand1":"a"},"$b0":{"mnemonic":"or","length":1,"cycle\
s":[4],"flags":["z","0","0","0"],"addr":"$b0","operand1":"b"},"$b1":{"mnemonic":\
"or","length":1,"cycles":[4],"flags":["z","0","0","0"],"addr":"$b1","operand1":"\
c"},"$b2":{"mnemonic":"or","length":1,"cycles":[4],"flags":["z","0","0","0"],"ad\
dr":"$b2","operand1":"d"},"$b3":{"mnemonic":"or","length":1,"cycles":[4],"flags"\
:["z","0","0","0"],"addr":"$b3","operand1":"e"},"$b4":{"mnemonic":"or","length":\
1,"cycles":[4],"flags":["z","0","0","0"],"addr":"$b4","operand1":"h"},"$b5":{"mn\
emonic":"or","length":1,"cycles":[4],"flags":["z","0","0","0"],"addr":"$b5","ope\
rand1":"l"},"$b6":{"mnemonic":"or","length":1,"cycles":[8],"flags":["z","0","0",\
"0"],"addr":"$b6","operand1":"(hl)"},"$b7":{"mnemonic":"or","length":1,"cycles":\
[4],"flags":["z","0","0","0"],"addr":"$b7","operand1":"a"},"$b8":{"mnemonic":"cp\
","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$b8","operand1":"b"}\
,"$b9":{"mnemonic":"cp","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr"\
:"$b9","operand1":"c"},"$ba":{"mnemonic":"cp","length":1,"cycles":[4],"flags":["\
z","1","h","c"],"addr":"$ba","operand1":"d"},"$bb":{"mnemonic":"cp","length":1,"\
cycles":[4],"flags":["z","1","h","c"],"addr":"$bb","operand1":"e"},"$bc":{"mnemo\
nic":"cp","length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$bc","operan\
d1":"h"},"$bd":{"mnemonic":"cp","length":1,"cycles":[4],"flags":["z","1","h","c"\
],"addr":"$bd","operand1":"l"},"$be":{"mnemonic":"cp","length":1,"cycles":[8],"f\
lags":["z","1","h","c"],"addr":"$be","operand1":"(hl)"},"$bf":{"mnemonic":"cp","\
length":1,"cycles":[4],"flags":["z","1","h","c"],"addr":"$bf","operand1":"a"},"$\
c0":{"mnemonic":"ret","length":1,"cycles":[20,8],"flags":["-","-","-","-"],"addr\
":"$c0","operand1":"nz"},"$c1":{"mnemonic":"pop","length":1,"cycles":[12],"flags\
":["-","-","-","-"],"addr":"$c1","operand1":"bc"},"$c2":{"mnemonic":"jp","length\
":3,"cycles":[16,12],"flags":["-","-","-","-"],"addr":"$c2","operand1":"nz","ope\
rand2":"a16"},"$c3":{"mnemonic":"jp","length":3,"cycles":[16],"flags":["-","-","\
-","-"],"addr":"$c3","operand1":"a16"},"$c4":{"mnemonic":"call","length":3,"cycl\
es":[24,12],"flags":["-","-","-","-"],"addr":"$c4","operand1":"nz","operand2":"a\
16"},"$c5":{"mnemonic":"push","length":1,"cycles":[16],"flags":["-","-","-","-"]\
,"addr":"$c5","operand1":"bc"},"$c6":{"mnemonic":"add","length":2,"cycles":[8],"\
flags":["z","0","h","c"],"addr":"$c6","operand1":"a","operand2":"d8"},"$c7":{"mn\
emonic":"rst","length":1,"cycles":[16],"flags":["-","-","-","-"],"addr":"$c7","o\
perand1":"00h"},"$c8":{"mnemonic":"ret","length":1,"cycles":[20,8],"flags":["-",\
"-","-","-"],"addr":"$c8","operand1":"z"},"$c9":{"mnemonic":"ret","length":1,"cy\
cles":[16],"flags":["-","-","-","-"],"addr":"$c9"},"$ca":{"mnemonic":"jp","lengt\
h":3,"cycles":[16,12],"flags":["-","-","-","-"],"addr":"$ca","operand1":"z","ope\
rand2":"a16"},"$cb":{"mnemonic":"prefix","length":1,"cycles":[4],"flags":["-","-\
","-","-"],"addr":"$cb","operand1":"cb"},"$cc":{"mnemonic":"call","length":3,"cy\
cles":[24,12],"flags":["-","-","-","-"],"addr":"$cc","operand1":"z","operand2":"\
a16"},"$cd":{"mnemonic":"call","length":3,"cycles":[24],"flags":["-","-","-","-"\
],"addr":"$cd","operand1":"a16"},"$ce":{"mnemonic":"adc","length":2,"cycles":[8]\
,"flags":["z","0","h","c"],"addr":"$ce","operand1":"a","operand2":"d8"},"$cf":{"\
mnemonic":"rst","length":1,"cycles":[16],"flags":["-","-","-","-"],"addr":"$cf",\
"operand1":"08h"},"$d0":{"mnemonic":"ret","length":1,"cycles":[20,8],"flags":["-\
","-","-","-"],"addr":"$d0","operand1":"nc"},"$d1":{"mnemonic":"pop","length":1,\
"cycles":[12],"flags":["-","-","-","-"],"addr":"$d1","operand1":"de"},"$d2":{"mn\
emonic":"jp","length":3,"cycles":[16,12],"flags":["-","-","-","-"],"addr":"$d2",\
"operand1":"nc","operand2":"a16"},"$d4":{"mnemonic":"call","length":3,"cycles":[\
24,12],"flags":["-","-","-","-"],"addr":"$d4","operand1":"nc","operand2":"a16"},\
"$d5":{"mnemonic":"push","length":1,"cycles":[16],"flags":["-","-","-","-"],"add\
r":"$d5","operand1":"de"},"$d6":{"mnemonic":"sub","length":2,"cycles":[8],"flags\
":["z","1","h","c"],"addr":"$d6","operand1":"d8"},"$d7":{"mnemonic":"rst","lengt\
h":1,"cycles":[16],"flags":["-","-","-","-"],"addr":"$d7","operand1":"10h"},"$d8\
":{"mnemonic":"ret","length":1,"cycles":[20,8],"flags":["-","-","-","-"],"addr":\
"$d8","operand1":"c"},"$d9":{"mnemonic":"reti","length":1,"cycles":[16],"flags":\
["-","-","-","-"],"addr":"$d9"},"$da":{"mnemonic":"jp","length":3,"cycles":[16,1\
2],"flags":["-","-","-","-"],"addr":"$da","operand1":"c","operand2":"a16"},"$dc"\
:{"mnemonic":"call","length":3,"cycles":[24,12],"flags":["-","-","-","-"],"addr"\
:"$dc","operand1":"c","operand2":"a16"},"$de":{"mnemonic":"sbc","length":2,"cycl\
es":[8],"flags":["z","1","h","c"],"addr":"$de","operand1":"a","operand2":"d8"},"\
$df":{"mnemonic":"rst","length":1,"cycles":[16],"flags":["-","-","-","-"],"addr"\
:"$df","operand1":"18h"},"$e0":{"mnemonic":"ldh","length":2,"cycles":[12],"flags\
":["-","-","-","-"],"addr":"$e0","operand1":"(a8)","operand2":"a"},"$e1":{"mnemo\
nic":"pop","length":1,"cycles":[12],"flags":["-","-","-","-"],"addr":"$e1","oper\
and1":"hl"},"$e2":{"mnemonic":"ld","length":2,"cycles":[8],"flags":["-","-","-",\
"-"],"addr":"$e2","operand1":"(c)","operand2":"a"},"$e5":{"mnemonic":"push","len\
gth":1,"cycles":[16],"flags":["-","-","-","-"],"addr":"$e5","operand1":"hl"},"$e\
6":{"mnemonic":"and","length":2,"cycles":[8],"flags":["z","0","1","0"],"addr":"$\
e6","operand1":"d8"},"$e7":{"mnemonic":"rst","length":1,"cycles":[16],"flags":["\
-","-","-","-"],"addr":"$e7","operand1":"20h"},"$e8":{"mnemonic":"add","length":\
2,"cycles":[16],"flags":["0","0","h","c"],"addr":"$e8","operand1":"sp","operand2\
":"r8"},"$e9":{"mnemonic":"jp","length":1,"cycles":[4],"flags":["-","-","-","-"]\
,"addr":"$e9","operand1":"(hl)"},"$ea":{"mnemonic":"ld","length":3,"cycles":[16]\
,"flags":["-","-","-","-"],"addr":"$ea","operand1":"(a16)","operand2":"a"},"$ee"\
:{"mnemonic":"xor","length":2,"cycles":[8],"flags":["z","0","0","0"],"addr":"$ee\
","operand1":"d8"},"$ef":{"mnemonic":"rst","length":1,"cycles":[16],"flags":["-"\
,"-","-","-"],"addr":"$ef","operand1":"28h"},"$f0":{"mnemonic":"ldh","length":2,\
"cycles":[12],"flags":["-","-","-","-"],"addr":"$f0","operand1":"a","operand2":"\
(a8)"},"$f1":{"mnemonic":"pop","length":1,"cycles":[12],"flags":["z","n","h","c"\
],"addr":"$f1","operand1":"af"},"$f2":{"mnemonic":"ld","length":2,"cycles":[8],"\
flags":["-","-","-","-"],"addr":"$f2","operand1":"a","operand2":"(c)"},"$f3":{"m\
nemonic":"di","length":1,"cycles":[4],"flags":["-","-","-","-"],"addr":"$f3"},"$\
f5":{"mnemonic":"push","length":1,"cycles":[16],"flags":["-","-","-","-"],"addr"\
:"$f5","operand1":"af"},"$f6":{"mnemonic":"or","length":2,"cycles":[8],"flags":[\
"z","0","0","0"],"addr":"$f6","operand1":"d8"},"$f7":{"mnemonic":"rst","length":\
1,"cycles":[16],"flags":["-","-","-","-"],"addr":"$f7","operand1":"30h"},"$f8":{\
"mnemonic":"ld","length":2,"cycles":[12],"flags":["0","0","h","c"],"addr":"$f8",\
"operand1":"hl","operand2":"sp+r8"},"$f9":{"mnemonic":"ld","length":1,"cycles":[\
8],"flags":["-","-","-","-"],"addr":"$f9","operand1":"sp","operand2":"hl"},"$fa"\
:{"mnemonic":"ld","length":3,"cycles":[16],"flags":["-","-","-","-"],"addr":"$fa\
","operand1":"a","operand2":"(a16)"},"$fb":{"mnemonic":"ei","length":1,"cycles":\
[4],"flags":["-","-","-","-"],"addr":"$fb"},"$fe":{"mnemonic":"cp","length":2,"c\
ycles":[8],"flags":["z","1","h","c"],"addr":"$fe","operand1":"d8"},"$ff":{"mnemo\
nic":"rst","length":1,"cycles":[16],"flags":["-","-","-","-"],"addr":"$ff","oper\
and1":"38h"},"$cb00":{"mnemonic":"rlc","length":2,"cycles":[8],"flags":["z","0",\
"0","c"],"addr":"$cb00","operand1":"b"},"$cb01":{"mnemonic":"rlc","length":2,"cy\
cles":[8],"flags":["z","0","0","c"],"addr":"$cb01","operand1":"c"},"$cb02":{"mne\
monic":"rlc","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb02","o\
perand1":"d"},"$cb03":{"mnemonic":"rlc","length":2,"cycles":[8],"flags":["z","0"\
,"0","c"],"addr":"$cb03","operand1":"e"},"$cb04":{"mnemonic":"rlc","length":2,"c\
ycles":[8],"flags":["z","0","0","c"],"addr":"$cb04","operand1":"h"},"$cb05":{"mn\
emonic":"rlc","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb05","\
operand1":"l"},"$cb06":{"mnemonic":"rlc","length":2,"cycles":[16],"flags":["z","\
0","0","c"],"addr":"$cb06","operand1":"(hl)"},"$cb07":{"mnemonic":"rlc","length"\
:2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb07","operand1":"a"},"$cb08"\
:{"mnemonic":"rrc","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb\
08","operand1":"b"},"$cb09":{"mnemonic":"rrc","length":2,"cycles":[8],"flags":["\
z","0","0","c"],"addr":"$cb09","operand1":"c"},"$cb0a":{"mnemonic":"rrc","length\
":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb0a","operand1":"d"},"$cb0b\
":{"mnemonic":"rrc","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$c\
b0b","operand1":"e"},"$cb0c":{"mnemonic":"rrc","length":2,"cycles":[8],"flags":[\
"z","0","0","c"],"addr":"$cb0c","operand1":"h"},"$cb0d":{"mnemonic":"rrc","lengt\
h":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb0d","operand1":"l"},"$cb0\
e":{"mnemonic":"rrc","length":2,"cycles":[16],"flags":["z","0","0","c"],"addr":"\
$cb0e","operand1":"(hl)"},"$cb0f":{"mnemonic":"rrc","length":2,"cycles":[8],"fla\
gs":["z","0","0","c"],"addr":"$cb0f","operand1":"a"},"$cb10":{"mnemonic":"rl","l\
ength":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb10","operand1":"b"},"\
$cb11":{"mnemonic":"rl","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr"\
:"$cb11","operand1":"c"},"$cb12":{"mnemonic":"rl","length":2,"cycles":[8],"flags\
":["z","0","0","c"],"addr":"$cb12","operand1":"d"},"$cb13":{"mnemonic":"rl","len\
gth":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb13","operand1":"e"},"$c\
b14":{"mnemonic":"rl","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"\
$cb14","operand1":"h"},"$cb15":{"mnemonic":"rl","length":2,"cycles":[8],"flags":\
["z","0","0","c"],"addr":"$cb15","operand1":"l"},"$cb16":{"mnemonic":"rl","lengt\
h":2,"cycles":[16],"flags":["z","0","0","c"],"addr":"$cb16","operand1":"(hl)"},"\
$cb17":{"mnemonic":"rl","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr"\
:"$cb17","operand1":"a"},"$cb18":{"mnemonic":"rr","length":2,"cycles":[8],"flags\
":["z","0","0","c"],"addr":"$cb18","operand1":"b"},"$cb19":{"mnemonic":"rr","len\
gth":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb19","operand1":"c"},"$c\
b1a":{"mnemonic":"rr","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"\
$cb1a","operand1":"d"},"$cb1b":{"mnemonic":"rr","length":2,"cycles":[8],"flags":\
["z","0","0","c"],"addr":"$cb1b","operand1":"e"},"$cb1c":{"mnemonic":"rr","lengt\
h":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb1c","operand1":"h"},"$cb1\
d":{"mnemonic":"rr","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$c\
b1d","operand1":"l"},"$cb1e":{"mnemonic":"rr","length":2,"cycles":[16],"flags":[\
"z","0","0","c"],"addr":"$cb1e","operand1":"(hl)"},"$cb1f":{"mnemonic":"rr","len\
gth":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb1f","operand1":"a"},"$c\
b20":{"mnemonic":"sla","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":\
"$cb20","operand1":"b"},"$cb21":{"mnemonic":"sla","length":2,"cycles":[8],"flags\
":["z","0","0","c"],"addr":"$cb21","operand1":"c"},"$cb22":{"mnemonic":"sla","le\
ngth":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb22","operand1":"d"},"$\
cb23":{"mnemonic":"sla","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr"\
:"$cb23","operand1":"e"},"$cb24":{"mnemonic":"sla","length":2,"cycles":[8],"flag\
s":["z","0","0","c"],"addr":"$cb24","operand1":"h"},"$cb25":{"mnemonic":"sla","l\
ength":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb25","operand1":"l"},"\
$cb26":{"mnemonic":"sla","length":2,"cycles":[16],"flags":["z","0","0","c"],"add\
r":"$cb26","operand1":"(hl)"},"$cb27":{"mnemonic":"sla","length":2,"cycles":[8],\
"flags":["z","0","0","c"],"addr":"$cb27","operand1":"a"},"$cb28":{"mnemonic":"sr\
a","length":2,"cycles":[8],"flags":["z","0","0","0"],"addr":"$cb28","operand1":"\
b"},"$cb29":{"mnemonic":"sra","length":2,"cycles":[8],"flags":["z","0","0","0"],\
"addr":"$cb29","operand1":"c"},"$cb2a":{"mnemonic":"sra","length":2,"cycles":[8]\
,"flags":["z","0","0","0"],"addr":"$cb2a","operand1":"d"},"$cb2b":{"mnemonic":"s\
ra","length":2,"cycles":[8],"flags":["z","0","0","0"],"addr":"$cb2b","operand1":\
"e"},"$cb2c":{"mnemonic":"sra","length":2,"cycles":[8],"flags":["z","0","0","0"]\
,"addr":"$cb2c","operand1":"h"},"$cb2d":{"mnemonic":"sra","length":2,"cycles":[8\
],"flags":["z","0","0","0"],"addr":"$cb2d","operand1":"l"},"$cb2e":{"mnemonic":"\
sra","length":2,"cycles":[16],"flags":["z","0","0","0"],"addr":"$cb2e","operand1\
":"(hl)"},"$cb2f":{"mnemonic":"sra","length":2,"cycles":[8],"flags":["z","0","0"\
,"0"],"addr":"$cb2f","operand1":"a"},"$cb30":{"mnemonic":"swap","length":2,"cycl\
es":[8],"flags":["z","0","0","0"],"addr":"$cb30","operand1":"b"},"$cb31":{"mnemo\
nic":"swap","length":2,"cycles":[8],"flags":["z","0","0","0"],"addr":"$cb31","op\
erand1":"c"},"$cb32":{"mnemonic":"swap","length":2,"cycles":[8],"flags":["z","0"\
,"0","0"],"addr":"$cb32","operand1":"d"},"$cb33":{"mnemonic":"swap","length":2,"\
cycles":[8],"flags":["z","0","0","0"],"addr":"$cb33","operand1":"e"},"$cb34":{"m\
nemonic":"swap","length":2,"cycles":[8],"flags":["z","0","0","0"],"addr":"$cb34"\
,"operand1":"h"},"$cb35":{"mnemonic":"swap","length":2,"cycles":[8],"flags":["z"\
,"0","0","0"],"addr":"$cb35","operand1":"l"},"$cb36":{"mnemonic":"swap","length"\
:2,"cycles":[16],"flags":["z","0","0","0"],"addr":"$cb36","operand1":"(hl)"},"$c\
b37":{"mnemonic":"swap","length":2,"cycles":[8],"flags":["z","0","0","0"],"addr"\
:"$cb37","operand1":"a"},"$cb38":{"mnemonic":"srl","length":2,"cycles":[8],"flag\
s":["z","0","0","c"],"addr":"$cb38","operand1":"b"},"$cb39":{"mnemonic":"srl","l\
ength":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb39","operand1":"c"},"\
$cb3a":{"mnemonic":"srl","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr\
":"$cb3a","operand1":"d"},"$cb3b":{"mnemonic":"srl","length":2,"cycles":[8],"fla\
gs":["z","0","0","c"],"addr":"$cb3b","operand1":"e"},"$cb3c":{"mnemonic":"srl","\
length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb3c","operand1":"h"},\
"$cb3d":{"mnemonic":"srl","length":2,"cycles":[8],"flags":["z","0","0","c"],"add\
r":"$cb3d","operand1":"l"},"$cb3e":{"mnemonic":"srl","length":2,"cycles":[16],"f\
lags":["z","0","0","c"],"addr":"$cb3e","operand1":"(hl)"},"$cb3f":{"mnemonic":"s\
rl","length":2,"cycles":[8],"flags":["z","0","0","c"],"addr":"$cb3f","operand1":\
"a"},"$cb40":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"]\
,"addr":"$cb40","operand1":"0","operand2":"b"},"$cb41":{"mnemonic":"bit","length\
":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb41","operand1":"0","operan\
d2":"c"},"$cb42":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1",\
"-"],"addr":"$cb42","operand1":"0","operand2":"d"},"$cb43":{"mnemonic":"bit","le\
ngth":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb43","operand1":"0","op\
erand2":"e"},"$cb44":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0",\
"1","-"],"addr":"$cb44","operand1":"0","operand2":"h"},"$cb45":{"mnemonic":"bit"\
,"length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb45","operand1":"0"\
,"operand2":"l"},"$cb46":{"mnemonic":"bit","length":2,"cycles":[16],"flags":["z"\
,"0","1","-"],"addr":"$cb46","operand1":"0","operand2":"(hl)"},"$cb47":{"mnemoni\
c":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb47","opera\
nd1":"0","operand2":"a"},"$cb48":{"mnemonic":"bit","length":2,"cycles":[8],"flag\
s":["z","0","1","-"],"addr":"$cb48","operand1":"1","operand2":"b"},"$cb49":{"mne\
monic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb49","o\
perand1":"1","operand2":"c"},"$cb4a":{"mnemonic":"bit","length":2,"cycles":[8],"\
flags":["z","0","1","-"],"addr":"$cb4a","operand1":"1","operand2":"d"},"$cb4b":{\
"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb4b\
","operand1":"1","operand2":"e"},"$cb4c":{"mnemonic":"bit","length":2,"cycles":[\
8],"flags":["z","0","1","-"],"addr":"$cb4c","operand1":"1","operand2":"h"},"$cb4\
d":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$\
cb4d","operand1":"1","operand2":"l"},"$cb4e":{"mnemonic":"bit","length":2,"cycle\
s":[16],"flags":["z","0","1","-"],"addr":"$cb4e","operand1":"1","operand2":"(hl)\
"},"$cb4f":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"\
addr":"$cb4f","operand1":"1","operand2":"a"},"$cb50":{"mnemonic":"bit","length":\
2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb50","operand1":"2","operand2\
":"b"},"$cb51":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-\
"],"addr":"$cb51","operand1":"2","operand2":"c"},"$cb52":{"mnemonic":"bit","leng\
th":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb52","operand1":"2","oper\
and2":"d"},"$cb53":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1\
","-"],"addr":"$cb53","operand1":"2","operand2":"e"},"$cb54":{"mnemonic":"bit","\
length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb54","operand1":"2","\
operand2":"h"},"$cb55":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0\
","1","-"],"addr":"$cb55","operand1":"2","operand2":"l"},"$cb56":{"mnemonic":"bi\
t","length":2,"cycles":[16],"flags":["z","0","1","-"],"addr":"$cb56","operand1":\
"2","operand2":"(hl)"},"$cb57":{"mnemonic":"bit","length":2,"cycles":[8],"flags"\
:["z","0","1","-"],"addr":"$cb57","operand1":"2","operand2":"a"},"$cb58":{"mnemo\
nic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb58","ope\
rand1":"3","operand2":"b"},"$cb59":{"mnemonic":"bit","length":2,"cycles":[8],"fl\
ags":["z","0","1","-"],"addr":"$cb59","operand1":"3","operand2":"c"},"$cb5a":{"m\
nemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb5a",\
"operand1":"3","operand2":"d"},"$cb5b":{"mnemonic":"bit","length":2,"cycles":[8]\
,"flags":["z","0","1","-"],"addr":"$cb5b","operand1":"3","operand2":"e"},"$cb5c"\
:{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb\
5c","operand1":"3","operand2":"h"},"$cb5d":{"mnemonic":"bit","length":2,"cycles"\
:[8],"flags":["z","0","1","-"],"addr":"$cb5d","operand1":"3","operand2":"l"},"$c\
b5e":{"mnemonic":"bit","length":2,"cycles":[16],"flags":["z","0","1","-"],"addr"\
:"$cb5e","operand1":"3","operand2":"(hl)"},"$cb5f":{"mnemonic":"bit","length":2,\
"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb5f","operand1":"3","operand2":\
"a"},"$cb60":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"]\
,"addr":"$cb60","operand1":"4","operand2":"b"},"$cb61":{"mnemonic":"bit","length\
":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb61","operand1":"4","operan\
d2":"c"},"$cb62":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1",\
"-"],"addr":"$cb62","operand1":"4","operand2":"d"},"$cb63":{"mnemonic":"bit","le\
ngth":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb63","operand1":"4","op\
erand2":"e"},"$cb64":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0",\
"1","-"],"addr":"$cb64","operand1":"4","operand2":"h"},"$cb65":{"mnemonic":"bit"\
,"length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb65","operand1":"4"\
,"operand2":"l"},"$cb66":{"mnemonic":"bit","length":2,"cycles":[16],"flags":["z"\
,"0","1","-"],"addr":"$cb66","operand1":"4","operand2":"(hl)"},"$cb67":{"mnemoni\
c":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb67","opera\
nd1":"4","operand2":"a"},"$cb68":{"mnemonic":"bit","length":2,"cycles":[8],"flag\
s":["z","0","1","-"],"addr":"$cb68","operand1":"5","operand2":"b"},"$cb69":{"mne\
monic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb69","o\
perand1":"5","operand2":"c"},"$cb6a":{"mnemonic":"bit","length":2,"cycles":[8],"\
flags":["z","0","1","-"],"addr":"$cb6a","operand1":"5","operand2":"d"},"$cb6b":{\
"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb6b\
","operand1":"5","operand2":"e"},"$cb6c":{"mnemonic":"bit","length":2,"cycles":[\
8],"flags":["z","0","1","-"],"addr":"$cb6c","operand1":"5","operand2":"h"},"$cb6\
d":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$\
cb6d","operand1":"5","operand2":"l"},"$cb6e":{"mnemonic":"bit","length":2,"cycle\
s":[16],"flags":["z","0","1","-"],"addr":"$cb6e","operand1":"5","operand2":"(hl)\
"},"$cb6f":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"\
addr":"$cb6f","operand1":"5","operand2":"a"},"$cb70":{"mnemonic":"bit","length":\
2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb70","operand1":"6","operand2\
":"b"},"$cb71":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-\
"],"addr":"$cb71","operand1":"6","operand2":"c"},"$cb72":{"mnemonic":"bit","leng\
th":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb72","operand1":"6","oper\
and2":"d"},"$cb73":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1\
","-"],"addr":"$cb73","operand1":"6","operand2":"e"},"$cb74":{"mnemonic":"bit","\
length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb74","operand1":"6","\
operand2":"h"},"$cb75":{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0\
","1","-"],"addr":"$cb75","operand1":"6","operand2":"l"},"$cb76":{"mnemonic":"bi\
t","length":2,"cycles":[16],"flags":["z","0","1","-"],"addr":"$cb76","operand1":\
"6","operand2":"(hl)"},"$cb77":{"mnemonic":"bit","length":2,"cycles":[8],"flags"\
:["z","0","1","-"],"addr":"$cb77","operand1":"6","operand2":"a"},"$cb78":{"mnemo\
nic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb78","ope\
rand1":"7","operand2":"b"},"$cb79":{"mnemonic":"bit","length":2,"cycles":[8],"fl\
ags":["z","0","1","-"],"addr":"$cb79","operand1":"7","operand2":"c"},"$cb7a":{"m\
nemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb7a",\
"operand1":"7","operand2":"d"},"$cb7b":{"mnemonic":"bit","length":2,"cycles":[8]\
,"flags":["z","0","1","-"],"addr":"$cb7b","operand1":"7","operand2":"e"},"$cb7c"\
:{"mnemonic":"bit","length":2,"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb\
7c","operand1":"7","operand2":"h"},"$cb7d":{"mnemonic":"bit","length":2,"cycles"\
:[8],"flags":["z","0","1","-"],"addr":"$cb7d","operand1":"7","operand2":"l"},"$c\
b7e":{"mnemonic":"bit","length":2,"cycles":[16],"flags":["z","0","1","-"],"addr"\
:"$cb7e","operand1":"7","operand2":"(hl)"},"$cb7f":{"mnemonic":"bit","length":2,\
"cycles":[8],"flags":["z","0","1","-"],"addr":"$cb7f","operand1":"7","operand2":\
"a"},"$cb80":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"]\
,"addr":"$cb80","operand1":"0","operand2":"b"},"$cb81":{"mnemonic":"res","length\
":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb81","operand1":"0","operan\
d2":"c"},"$cb82":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-",\
"-"],"addr":"$cb82","operand1":"0","operand2":"d"},"$cb83":{"mnemonic":"res","le\
ngth":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb83","operand1":"0","op\
erand2":"e"},"$cb84":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-",\
"-","-"],"addr":"$cb84","operand1":"0","operand2":"h"},"$cb85":{"mnemonic":"res"\
,"length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb85","operand1":"0"\
,"operand2":"l"},"$cb86":{"mnemonic":"res","length":2,"cycles":[16],"flags":["-"\
,"-","-","-"],"addr":"$cb86","operand1":"0","operand2":"(hl)"},"$cb87":{"mnemoni\
c":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb87","opera\
nd1":"0","operand2":"a"},"$cb88":{"mnemonic":"res","length":2,"cycles":[8],"flag\
s":["-","-","-","-"],"addr":"$cb88","operand1":"1","operand2":"b"},"$cb89":{"mne\
monic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb89","o\
perand1":"1","operand2":"c"},"$cb8a":{"mnemonic":"res","length":2,"cycles":[8],"\
flags":["-","-","-","-"],"addr":"$cb8a","operand1":"1","operand2":"d"},"$cb8b":{\
"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb8b\
","operand1":"1","operand2":"e"},"$cb8c":{"mnemonic":"res","length":2,"cycles":[\
8],"flags":["-","-","-","-"],"addr":"$cb8c","operand1":"1","operand2":"h"},"$cb8\
d":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$\
cb8d","operand1":"1","operand2":"l"},"$cb8e":{"mnemonic":"res","length":2,"cycle\
s":[16],"flags":["-","-","-","-"],"addr":"$cb8e","operand1":"1","operand2":"(hl)\
"},"$cb8f":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"\
addr":"$cb8f","operand1":"1","operand2":"a"},"$cb90":{"mnemonic":"res","length":\
2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb90","operand1":"2","operand2\
":"b"},"$cb91":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-\
"],"addr":"$cb91","operand1":"2","operand2":"c"},"$cb92":{"mnemonic":"res","leng\
th":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb92","operand1":"2","oper\
and2":"d"},"$cb93":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-\
","-"],"addr":"$cb93","operand1":"2","operand2":"e"},"$cb94":{"mnemonic":"res","\
length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb94","operand1":"2","\
operand2":"h"},"$cb95":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-\
","-","-"],"addr":"$cb95","operand1":"2","operand2":"l"},"$cb96":{"mnemonic":"re\
s","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr":"$cb96","operand1":\
"2","operand2":"(hl)"},"$cb97":{"mnemonic":"res","length":2,"cycles":[8],"flags"\
:["-","-","-","-"],"addr":"$cb97","operand1":"2","operand2":"a"},"$cb98":{"mnemo\
nic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb98","ope\
rand1":"3","operand2":"b"},"$cb99":{"mnemonic":"res","length":2,"cycles":[8],"fl\
ags":["-","-","-","-"],"addr":"$cb99","operand1":"3","operand2":"c"},"$cb9a":{"m\
nemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb9a",\
"operand1":"3","operand2":"d"},"$cb9b":{"mnemonic":"res","length":2,"cycles":[8]\
,"flags":["-","-","-","-"],"addr":"$cb9b","operand1":"3","operand2":"e"},"$cb9c"\
:{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb\
9c","operand1":"3","operand2":"h"},"$cb9d":{"mnemonic":"res","length":2,"cycles"\
:[8],"flags":["-","-","-","-"],"addr":"$cb9d","operand1":"3","operand2":"l"},"$c\
b9e":{"mnemonic":"res","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr"\
:"$cb9e","operand1":"3","operand2":"(hl)"},"$cb9f":{"mnemonic":"res","length":2,\
"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb9f","operand1":"3","operand2":\
"a"},"$cba0":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"]\
,"addr":"$cba0","operand1":"4","operand2":"b"},"$cba1":{"mnemonic":"res","length\
":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cba1","operand1":"4","operan\
d2":"c"},"$cba2":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-",\
"-"],"addr":"$cba2","operand1":"4","operand2":"d"},"$cba3":{"mnemonic":"res","le\
ngth":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cba3","operand1":"4","op\
erand2":"e"},"$cba4":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-",\
"-","-"],"addr":"$cba4","operand1":"4","operand2":"h"},"$cba5":{"mnemonic":"res"\
,"length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cba5","operand1":"4"\
,"operand2":"l"},"$cba6":{"mnemonic":"res","length":2,"cycles":[16],"flags":["-"\
,"-","-","-"],"addr":"$cba6","operand1":"4","operand2":"(hl)"},"$cba7":{"mnemoni\
c":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cba7","opera\
nd1":"4","operand2":"a"},"$cba8":{"mnemonic":"res","length":2,"cycles":[8],"flag\
s":["-","-","-","-"],"addr":"$cba8","operand1":"5","operand2":"b"},"$cba9":{"mne\
monic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cba9","o\
perand1":"5","operand2":"c"},"$cbaa":{"mnemonic":"res","length":2,"cycles":[8],"\
flags":["-","-","-","-"],"addr":"$cbaa","operand1":"5","operand2":"d"},"$cbab":{\
"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbab\
","operand1":"5","operand2":"e"},"$cbac":{"mnemonic":"res","length":2,"cycles":[\
8],"flags":["-","-","-","-"],"addr":"$cbac","operand1":"5","operand2":"h"},"$cba\
d":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$\
cbad","operand1":"5","operand2":"l"},"$cbae":{"mnemonic":"res","length":2,"cycle\
s":[16],"flags":["-","-","-","-"],"addr":"$cbae","operand1":"5","operand2":"(hl)\
"},"$cbaf":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"\
addr":"$cbaf","operand1":"5","operand2":"a"},"$cbb0":{"mnemonic":"res","length":\
2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbb0","operand1":"6","operand2\
":"b"},"$cbb1":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-\
"],"addr":"$cbb1","operand1":"6","operand2":"c"},"$cbb2":{"mnemonic":"res","leng\
th":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbb2","operand1":"6","oper\
and2":"d"},"$cbb3":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-\
","-"],"addr":"$cbb3","operand1":"6","operand2":"e"},"$cbb4":{"mnemonic":"res","\
length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbb4","operand1":"6","\
operand2":"h"},"$cbb5":{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-\
","-","-"],"addr":"$cbb5","operand1":"6","operand2":"l"},"$cbb6":{"mnemonic":"re\
s","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr":"$cbb6","operand1":\
"6","operand2":"(hl)"},"$cbb7":{"mnemonic":"res","length":2,"cycles":[8],"flags"\
:["-","-","-","-"],"addr":"$cbb7","operand1":"6","operand2":"a"},"$cbb8":{"mnemo\
nic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbb8","ope\
rand1":"7","operand2":"b"},"$cbb9":{"mnemonic":"res","length":2,"cycles":[8],"fl\
ags":["-","-","-","-"],"addr":"$cbb9","operand1":"7","operand2":"c"},"$cbba":{"m\
nemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbba",\
"operand1":"7","operand2":"d"},"$cbbb":{"mnemonic":"res","length":2,"cycles":[8]\
,"flags":["-","-","-","-"],"addr":"$cbbb","operand1":"7","operand2":"e"},"$cbbc"\
:{"mnemonic":"res","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb\
bc","operand1":"7","operand2":"h"},"$cbbd":{"mnemonic":"res","length":2,"cycles"\
:[8],"flags":["-","-","-","-"],"addr":"$cbbd","operand1":"7","operand2":"l"},"$c\
bbe":{"mnemonic":"res","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr"\
:"$cbbe","operand1":"7","operand2":"(hl)"},"$cbbf":{"mnemonic":"res","length":2,\
"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbbf","operand1":"7","operand2":\
"a"},"$cbc0":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"]\
,"addr":"$cbc0","operand1":"0","operand2":"b"},"$cbc1":{"mnemonic":"set","length\
":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbc1","operand1":"0","operan\
d2":"c"},"$cbc2":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-",\
"-"],"addr":"$cbc2","operand1":"0","operand2":"d"},"$cbc3":{"mnemonic":"set","le\
ngth":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbc3","operand1":"0","op\
erand2":"e"},"$cbc4":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-",\
"-","-"],"addr":"$cbc4","operand1":"0","operand2":"h"},"$cbc5":{"mnemonic":"set"\
,"length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbc5","operand1":"0"\
,"operand2":"l"},"$cbc6":{"mnemonic":"set","length":2,"cycles":[16],"flags":["-"\
,"-","-","-"],"addr":"$cbc6","operand1":"0","operand2":"(hl)"},"$cbc7":{"mnemoni\
c":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbc7","opera\
nd1":"0","operand2":"a"},"$cbc8":{"mnemonic":"set","length":2,"cycles":[8],"flag\
s":["-","-","-","-"],"addr":"$cbc8","operand1":"1","operand2":"b"},"$cbc9":{"mne\
monic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbc9","o\
perand1":"1","operand2":"c"},"$cbca":{"mnemonic":"set","length":2,"cycles":[8],"\
flags":["-","-","-","-"],"addr":"$cbca","operand1":"1","operand2":"d"},"$cbcb":{\
"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbcb\
","operand1":"1","operand2":"e"},"$cbcc":{"mnemonic":"set","length":2,"cycles":[\
8],"flags":["-","-","-","-"],"addr":"$cbcc","operand1":"1","operand2":"h"},"$cbc\
d":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$\
cbcd","operand1":"1","operand2":"l"},"$cbce":{"mnemonic":"set","length":2,"cycle\
s":[16],"flags":["-","-","-","-"],"addr":"$cbce","operand1":"1","operand2":"(hl)\
"},"$cbcf":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"\
addr":"$cbcf","operand1":"1","operand2":"a"},"$cbd0":{"mnemonic":"set","length":\
2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbd0","operand1":"2","operand2\
":"b"},"$cbd1":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-\
"],"addr":"$cbd1","operand1":"2","operand2":"c"},"$cbd2":{"mnemonic":"set","leng\
th":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbd2","operand1":"2","oper\
and2":"d"},"$cbd3":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-\
","-"],"addr":"$cbd3","operand1":"2","operand2":"e"},"$cbd4":{"mnemonic":"set","\
length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbd4","operand1":"2","\
operand2":"h"},"$cbd5":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-\
","-","-"],"addr":"$cbd5","operand1":"2","operand2":"l"},"$cbd6":{"mnemonic":"se\
t","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr":"$cbd6","operand1":\
"2","operand2":"(hl)"},"$cbd7":{"mnemonic":"set","length":2,"cycles":[8],"flags"\
:["-","-","-","-"],"addr":"$cbd7","operand1":"2","operand2":"a"},"$cbd8":{"mnemo\
nic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbd8","ope\
rand1":"3","operand2":"b"},"$cbd9":{"mnemonic":"set","length":2,"cycles":[8],"fl\
ags":["-","-","-","-"],"addr":"$cbd9","operand1":"3","operand2":"c"},"$cbda":{"m\
nemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbda",\
"operand1":"3","operand2":"d"},"$cbdb":{"mnemonic":"set","length":2,"cycles":[8]\
,"flags":["-","-","-","-"],"addr":"$cbdb","operand1":"3","operand2":"e"},"$cbdc"\
:{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb\
dc","operand1":"3","operand2":"h"},"$cbdd":{"mnemonic":"set","length":2,"cycles"\
:[8],"flags":["-","-","-","-"],"addr":"$cbdd","operand1":"3","operand2":"l"},"$c\
bde":{"mnemonic":"set","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr"\
:"$cbde","operand1":"3","operand2":"(hl)"},"$cbdf":{"mnemonic":"set","length":2,\
"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbdf","operand1":"3","operand2":\
"a"},"$cbe0":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"]\
,"addr":"$cbe0","operand1":"4","operand2":"b"},"$cbe1":{"mnemonic":"set","length\
":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbe1","operand1":"4","operan\
d2":"c"},"$cbe2":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-",\
"-"],"addr":"$cbe2","operand1":"4","operand2":"d"},"$cbe3":{"mnemonic":"set","le\
ngth":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbe3","operand1":"4","op\
erand2":"e"},"$cbe4":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-",\
"-","-"],"addr":"$cbe4","operand1":"4","operand2":"h"},"$cbe5":{"mnemonic":"set"\
,"length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbe5","operand1":"4"\
,"operand2":"l"},"$cbe6":{"mnemonic":"set","length":2,"cycles":[16],"flags":["-"\
,"-","-","-"],"addr":"$cbe6","operand1":"4","operand2":"(hl)"},"$cbe7":{"mnemoni\
c":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbe7","opera\
nd1":"4","operand2":"a"},"$cbe8":{"mnemonic":"set","length":2,"cycles":[8],"flag\
s":["-","-","-","-"],"addr":"$cbe8","operand1":"5","operand2":"b"},"$cbe9":{"mne\
monic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbe9","o\
perand1":"5","operand2":"c"},"$cbea":{"mnemonic":"set","length":2,"cycles":[8],"\
flags":["-","-","-","-"],"addr":"$cbea","operand1":"5","operand2":"d"},"$cbeb":{\
"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbeb\
","operand1":"5","operand2":"e"},"$cbec":{"mnemonic":"set","length":2,"cycles":[\
8],"flags":["-","-","-","-"],"addr":"$cbec","operand1":"5","operand2":"h"},"$cbe\
d":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$\
cbed","operand1":"5","operand2":"l"},"$cbee":{"mnemonic":"set","length":2,"cycle\
s":[16],"flags":["-","-","-","-"],"addr":"$cbee","operand1":"5","operand2":"(hl)\
"},"$cbef":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"\
addr":"$cbef","operand1":"5","operand2":"a"},"$cbf0":{"mnemonic":"set","length":\
2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbf0","operand1":"6","operand2\
":"b"},"$cbf1":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-\
"],"addr":"$cbf1","operand1":"6","operand2":"c"},"$cbf2":{"mnemonic":"set","leng\
th":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbf2","operand1":"6","oper\
and2":"d"},"$cbf3":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-\
","-"],"addr":"$cbf3","operand1":"6","operand2":"e"},"$cbf4":{"mnemonic":"set","\
length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbf4","operand1":"6","\
operand2":"h"},"$cbf5":{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-\
","-","-"],"addr":"$cbf5","operand1":"6","operand2":"l"},"$cbf6":{"mnemonic":"se\
t","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr":"$cbf6","operand1":\
"6","operand2":"(hl)"},"$cbf7":{"mnemonic":"set","length":2,"cycles":[8],"flags"\
:["-","-","-","-"],"addr":"$cbf7","operand1":"6","operand2":"a"},"$cbf8":{"mnemo\
nic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbf8","ope\
rand1":"7","operand2":"b"},"$cbf9":{"mnemonic":"set","length":2,"cycles":[8],"fl\
ags":["-","-","-","-"],"addr":"$cbf9","operand1":"7","operand2":"c"},"$cbfa":{"m\
nemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbfa",\
"operand1":"7","operand2":"d"},"$cbfb":{"mnemonic":"set","length":2,"cycles":[8]\
,"flags":["-","-","-","-"],"addr":"$cbfb","operand1":"7","operand2":"e"},"$cbfc"\
:{"mnemonic":"set","length":2,"cycles":[8],"flags":["-","-","-","-"],"addr":"$cb\
fc","operand1":"7","operand2":"h"},"$cbfd":{"mnemonic":"set","length":2,"cycles"\
:[8],"flags":["-","-","-","-"],"addr":"$cbfd","operand1":"7","operand2":"l"},"$c\
bfe":{"mnemonic":"set","length":2,"cycles":[16],"flags":["-","-","-","-"],"addr"\
:"$cbfe","operand1":"7","operand2":"(hl)"},"$cbff":{"mnemonic":"set","length":2,\
"cycles":[8],"flags":["-","-","-","-"],"addr":"$cbff","operand1":"7","operand2":\
"a"}}
"""
        # if not instance....
            cls.instance.length = len(cls.instance.json)
        return cls.instance
